/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;
/**
 *
 * @author Malkhan Singh
 */
public class CalculatorUI extends javax.swing.JFrame {
    private String strResult = "";
    /**
     * Creates new form CalculatorUI
     */
    public CalculatorUI() {
        initComponents();
        setVisible(true);
    }
    public void setTxtResult(String str){
        txtResult.setText(str);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResult = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnMultiplication = new javax.swing.JButton();
        btnSubstraction = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnAddison = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnDecimalPoint = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnModulation = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnExponential = new javax.swing.JButton();
        btnOpenBracket = new javax.swing.JButton();
        btnCloseBracket = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnPow = new javax.swing.JButton();
        btnLn = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnDeg = new javax.swing.JButton();
        btnRad = new javax.swing.JButton();
        btnAsin = new javax.swing.JButton();
        btnAcos = new javax.swing.JButton();
        btnAtan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResult.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("CALCULATOR");

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 153, 255));
        btnClear.setText("C");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnDivision.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(0, 153, 255));
        btnDivision.setText("/");
        btnDivision.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivisionMouseClicked(evt);
            }
        });

        btnMultiplication.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnMultiplication.setForeground(new java.awt.Color(0, 153, 255));
        btnMultiplication.setText("*");
        btnMultiplication.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMultiplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiplicationMouseClicked(evt);
            }
        });

        btnSubstraction.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnSubstraction.setForeground(new java.awt.Color(0, 153, 255));
        btnSubstraction.setText("-");
        btnSubstraction.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubstraction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubstractionMouseClicked(evt);
            }
        });

        btnSeven.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnSeven.setForeground(new java.awt.Color(0, 153, 255));
        btnSeven.setText("7");
        btnSeven.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSeven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSevenMouseClicked(evt);
            }
        });

        btnEight.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnEight.setForeground(new java.awt.Color(0, 153, 255));
        btnEight.setText("8");
        btnEight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEightMouseClicked(evt);
            }
        });

        btnNine.setBackground(new java.awt.Color(255, 255, 255));
        btnNine.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnNine.setForeground(new java.awt.Color(0, 153, 255));
        btnNine.setText("9");
        btnNine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNineMouseClicked(evt);
            }
        });

        btnAddison.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnAddison.setForeground(new java.awt.Color(0, 153, 255));
        btnAddison.setText("+");
        btnAddison.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddison.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddisonMouseClicked(evt);
            }
        });

        btnFour.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnFour.setForeground(new java.awt.Color(0, 153, 255));
        btnFour.setText("4");
        btnFour.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFourMouseClicked(evt);
            }
        });

        btnFive.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnFive.setForeground(new java.awt.Color(0, 153, 255));
        btnFive.setText("5");
        btnFive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiveMouseClicked(evt);
            }
        });

        btnSix.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnSix.setForeground(new java.awt.Color(0, 153, 255));
        btnSix.setText("6");
        btnSix.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSixMouseClicked(evt);
            }
        });
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnDecimalPoint.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnDecimalPoint.setForeground(new java.awt.Color(0, 153, 255));
        btnDecimalPoint.setText(".");
        btnDecimalPoint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDecimalPoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDecimalPointMouseClicked(evt);
            }
        });

        btnOne.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnOne.setForeground(new java.awt.Color(0, 153, 255));
        btnOne.setText("1");
        btnOne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOneMouseClicked(evt);
            }
        });

        btnTwo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnTwo.setForeground(new java.awt.Color(0, 153, 255));
        btnTwo.setText("2");
        btnTwo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTwoMouseClicked(evt);
            }
        });

        btnThree.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnThree.setForeground(new java.awt.Color(0, 153, 255));
        btnThree.setText("3");
        btnThree.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThreeMouseClicked(evt);
            }
        });

        btnPi.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnPi.setForeground(new java.awt.Color(0, 153, 255));
        btnPi.setText("π");
        btnPi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPiMouseClicked(evt);
            }
        });

        btnZero.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnZero.setForeground(new java.awt.Color(0, 153, 255));
        btnZero.setText("0");
        btnZero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnZero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnZeroMouseClicked(evt);
            }
        });

        btnModulation.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnModulation.setForeground(new java.awt.Color(0, 153, 255));
        btnModulation.setText("%");
        btnModulation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModulation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModulationMouseClicked(evt);
            }
        });

        btnEqual.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnEqual.setForeground(new java.awt.Color(0, 153, 255));
        btnEqual.setText("=");
        btnEqual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEqual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEqualMouseClicked(evt);
            }
        });

        btnExponential.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnExponential.setForeground(new java.awt.Color(0, 153, 255));
        btnExponential.setText("^");
        btnExponential.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExponential.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExponentialMouseClicked(evt);
            }
        });

        btnOpenBracket.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnOpenBracket.setForeground(new java.awt.Color(0, 153, 255));
        btnOpenBracket.setText("(");
        btnOpenBracket.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOpenBracket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpenBracketMouseClicked(evt);
            }
        });

        btnCloseBracket.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnCloseBracket.setForeground(new java.awt.Color(0, 153, 255));
        btnCloseBracket.setText(")");
        btnCloseBracket.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCloseBracket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseBracketMouseClicked(evt);
            }
        });

        btnBackspace.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnBackspace.setForeground(new java.awt.Color(0, 153, 255));
        btnBackspace.setText("<-");
        btnBackspace.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackspace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackspaceMouseClicked(evt);
            }
        });

        btnCos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCos.setForeground(new java.awt.Color(0, 153, 255));
        btnCos.setText("cos");
        btnCos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCosMouseClicked(evt);
            }
        });

        btnSin.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSin.setForeground(new java.awt.Color(0, 153, 255));
        btnSin.setText("sin");
        btnSin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSinMouseClicked(evt);
            }
        });

        btnTan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnTan.setForeground(new java.awt.Color(0, 153, 255));
        btnTan.setText("tan");
        btnTan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTanMouseClicked(evt);
            }
        });

        btnPow.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnPow.setForeground(new java.awt.Color(0, 153, 255));
        btnPow.setText("pow");
        btnPow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPowMouseClicked(evt);
            }
        });

        btnLn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnLn.setForeground(new java.awt.Color(0, 153, 255));
        btnLn.setText("ln");
        btnLn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLnMouseClicked(evt);
            }
        });

        btnLog.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnLog.setForeground(new java.awt.Color(0, 153, 255));
        btnLog.setText("log");
        btnLog.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogMouseClicked(evt);
            }
        });

        btnSqrt.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSqrt.setForeground(new java.awt.Color(0, 153, 255));
        btnSqrt.setText("sqrt");
        btnSqrt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSqrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSqrtMouseClicked(evt);
            }
        });

        btnDeg.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDeg.setForeground(new java.awt.Color(0, 153, 255));
        btnDeg.setText("deg");
        btnDeg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDegMouseClicked(evt);
            }
        });

        btnRad.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnRad.setForeground(new java.awt.Color(0, 153, 255));
        btnRad.setText("rad");
        btnRad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRadMouseClicked(evt);
            }
        });

        btnAsin.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnAsin.setForeground(new java.awt.Color(0, 153, 255));
        btnAsin.setText("asin");
        btnAsin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAsin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsinMouseClicked(evt);
            }
        });

        btnAcos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnAcos.setForeground(new java.awt.Color(0, 153, 255));
        btnAcos.setText("acos");
        btnAcos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAcos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcosMouseClicked(evt);
            }
        });

        btnAtan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnAtan.setForeground(new java.awt.Color(0, 153, 255));
        btnAtan.setText("atan");
        btnAtan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResult, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnOne, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(btnPi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnTwo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnOpenBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCloseBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnModulation, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAcos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnDecimalPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnRad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAsin, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(btnLn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAtan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeg, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(btnLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnExponential, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnSeven, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(btnFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMultiplication, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(btnNine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnSubstraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddison, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSin, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(btnTan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPow, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSubstraction, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnExponential, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDivision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddison, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLog, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(btnLn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDecimalPoint, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(btnSix, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addComponent(btnFive, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(btnFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModulation, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btnAcos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCloseBracket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btnOpenBracket, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAsin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btnBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSevenMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnSeven.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnSevenMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        strResult = "";
        setTxtResult(strResult);
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnEightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEightMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnEight.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnEightMouseClicked

    private void btnNineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNineMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnNine.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnNineMouseClicked

    private void btnAddisonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddisonMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnAddison.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnAddisonMouseClicked

    private void btnFourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFourMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnFour.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnFourMouseClicked

    private void btnFiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiveMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnFive.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnFiveMouseClicked

    private void btnSixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSixMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnSix.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnSixMouseClicked

    private void btnOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOneMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnOne.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnOneMouseClicked

    private void btnTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTwoMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnTwo.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnTwoMouseClicked

    private void btnThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThreeMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnThree.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnThreeMouseClicked

    private void btnEqualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqualMouseClicked
        // TODO add your handling code here:
        Calculator clc = new Calculator();
        System.out.println(strResult);
       double result = clc.evaluate(strResult);
       txtResult.setText(Double.toString(result));
       strResult = "";
    }//GEN-LAST:event_btnEqualMouseClicked

    private void btnPiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPiMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnPi.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnPiMouseClicked

    private void btnZeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnZeroMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnZero.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnZeroMouseClicked

    private void btnModulationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModulationMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnModulation.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnModulationMouseClicked

    private void btnExponentialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExponentialMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnExponential.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnExponentialMouseClicked

    private void btnOpenBracketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenBracketMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnOpenBracket.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnOpenBracketMouseClicked

    private void btnCloseBracketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseBracketMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnCloseBracket.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnCloseBracketMouseClicked

    private void btnBackspaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackspaceMouseClicked
        // TODO add your handling code here:
        strResult = txtResult.getText();
        int l = strResult.length();
        if(l>0){
            strResult = strResult.substring(0,l-1);
            setTxtResult(strResult);
        } 
    }//GEN-LAST:event_btnBackspaceMouseClicked

    private void btnSubstractionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubstractionMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnSubstraction.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnSubstractionMouseClicked

    private void btnDecimalPointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDecimalPointMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnDecimalPoint.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnDecimalPointMouseClicked

    private void btnDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisionMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnDivision.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnDivisionMouseClicked

    private void btnMultiplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplicationMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnMultiplication.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnMultiplicationMouseClicked

    private void btnCosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCosMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnCos.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnCosMouseClicked

    private void btnSinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSinMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnSin.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnSinMouseClicked

    private void btnTanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTanMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnTan.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnTanMouseClicked

    private void btnPowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPowMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnPow.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnPowMouseClicked

    private void btnLnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLnMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnLn.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnLnMouseClicked

    private void btnLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnLog.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnLogMouseClicked

    private void btnSqrtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqrtMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnSqrt.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnSqrtMouseClicked

    private void btnDegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDegMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnDeg.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnDegMouseClicked

    private void btnRadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRadMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnRad.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnRadMouseClicked

    private void btnAsinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsinMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnAsin.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnAsinMouseClicked

    private void btnAcosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcosMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnAcos.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnAcosMouseClicked

    private void btnAtanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtanMouseClicked
        // TODO add your handling code here:
        strResult = strResult + btnAtan.getText();
        setTxtResult(strResult);
    }//GEN-LAST:event_btnAtanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
            CalculatorUI clcUI = new CalculatorUI();
            Calculator clc = new Calculator();
//            System.out.println(clc.evaluate("100-(9+500)"));
//            System.out.println(clc.evaluate("sin(30)"));
//            System.out.println(clc.evaluate("100 * ( 2 + 12 )"));
//            System.out.println(clc.evaluate("100 * ( 2 + 12 ) / 14"));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcos;
    private javax.swing.JButton btnAddison;
    private javax.swing.JButton btnAsin;
    private javax.swing.JButton btnAtan;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCloseBracket;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDecimalPoint;
    private javax.swing.JButton btnDeg;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnExponential;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnLn;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnModulation;
    private javax.swing.JButton btnMultiplication;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnOpenBracket;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPow;
    private javax.swing.JButton btnRad;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSubstraction;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
