/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizapp;
import java.sql.*;
/**
 *
 * @author student
 */
public class QuizAppUI extends javax.swing.JFrame {

    /**
     * Creates new form QuizAppUI
     */
    public QuizAppUI() {
        initComponents();
        setVisible(true);
        
    }
    void login(){
        String name = txtName.getText();
        String rollNumber = txtRollNumber.getText();
        try{           
       Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz?" + "user=root&password=");     
       PreparedStatement pst = conn.prepareStatement("INSERT INTO students(name, roll_no)"+" values(?, ?)");
       pst.setString(1, name); 
       pst.setString(2, rollNumber);
       pst.execute();
       pst.close();
   }
   catch(Exception e){
       e.printStackTrace();
       System.out.println("Failed with Exception!");
   }
    }
    void getQuestion(int qId){
        try{           
       Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz?" + "user=root&password=");     
       PreparedStatement pst = conn.prepareStatement("SELECT * FROM questions WHERE questionId = ?");
       pst.setInt(1, qId);
       ResultSet rs = pst.executeQuery();
       
       while(rs.next()){
         //Retrieve by column name
         int questionId  = rs.getInt("questionId");
         String question = rs.getString("question");
         String option1 = rs.getString("option1");
         String option2 = rs.getString("option2");
         String option3 = rs.getString("option3");
         String option4 = rs.getString("option4");
         
         //Display values
         System.out.print("ID: " + questionId);
         System.out.println(", Question: " + question);
         System.out.println(", option1: " + option1);
         System.out.println(", option2: " + option2);
         System.out.println(", option3: " + option3);
         System.out.println(", option4: " + option4);
         
         lblQuestion.setText(question);
         jRadioButton2.setText(option1);
         jRadioButton1.setText(option2);
         jRadioButton3.setText(option3);
         btnOption4.setText(option4);
      }
   }
   catch(Exception e){
       e.printStackTrace();
       System.out.println("Failed with Exception!");
   }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutStyle1 = new org.jdesktop.layout.LayoutStyle();
        jFrame1 = new javax.swing.JFrame();
        btnSubmitQuestion = new javax.swing.JButton();
        lblQuestion = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        btnOption4 = new javax.swing.JRadioButton();
        layoutStyle2 = new org.jdesktop.layout.LayoutStyle();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRollNumber = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSubmitQuestion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSubmitQuestion.setText("Submit");
        btnSubmitQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmitQuestion)
                .addGap(150, 150, 150))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOption4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOption4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnSubmitQuestion)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setText("Welcome!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 13, -1, 34));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 117, 156, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Enter Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 117, -1, 22));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Enter Roll No. :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 157, -1, 22));
        getContentPane().add(txtRollNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 157, 156, -1));

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSubmit.setText("Start Test");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 233, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
//        login();
//            jFrame1.setPreferredSize(new Dimension(400, 300));
//            jFrame1.pack();
//            jFrame1.setLocationRelativeTo(null);
            jFrame1.setVisible(true);
            getQuestion(1);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSubmitQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnOption4;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmitQuestion;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private org.jdesktop.layout.LayoutStyle layoutStyle1;
    private org.jdesktop.layout.LayoutStyle layoutStyle2;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRollNumber;
    // End of variables declaration//GEN-END:variables
}
